import type { Metadata } from "next";
import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import PageWrapper from "@/components/PageWrapper";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-white font-sans antialiased text-zinc-600",
          process.env.NODE_ENV === "development" && "debug-screens",
          fontSans.variable
        )}
      >
        <PageWrapper>{children}</PageWrapper>
      </body>
    </html>
  );
}
